### ISSUE TITLE
Mansion start is unable to be generated

### ISSUE THREAD

**Issue by miu135** [Taberone/Cataclysm-DDA-Touhou-Mod#26]
Can't seem to start in a mansion cause the game won't let me. Did the mansion start got removed?

**Comment by Taberone** [comment]
Will look into

**Comment by Taberone** [comment]
~~I'm not getting it on my end for some reason. Could you try a clean reinstall of the mod? (Delete the Touhou folder under Mods, reinstall the folder into Mods).~~

EDIT: Hold on, now I'm getting it. Weird. Still looking into it.

Check your "Size of Cities" and "City Spacing" settings. See if these will still result in the mansion start error?
![image](https://user-images.githubusercontent.com/9733597/79390640-ee319b00-7f24-11ea-8864-b7445c1b71f9.png)

**Comment by miu135** [comment]
Tried playing it on default world setting
![cdda1](https://user-images.githubusercontent.com/54433550/79406367-1b338b80-7fc1-11ea-8e84-d6f4da77465a.PNG)

On a mansion start
![cdda2](https://user-images.githubusercontent.com/54433550/79406396-2ab2d480-7fc1-11ea-9064-68ab23aafa76.PNG)

Here's the result
![cdda3](https://user-images.githubusercontent.com/54433550/79406409-343c3c80-7fc1-11ea-9df6-5de5fe51a9e7.PNG)

(I think this is because they removed the mansion start scenario completely since I just noticed that the starting scenario 'Mansion holdout' is nowhere to be found)

**Comment by Taberone** [comment]
It still works for me, for some reason. What version of CDDA are you using? I use CDDA Launcher and it tells me that my version is:

0.E-732-gd0f0a96 (tiles, experimental?)
Build 10533 (a day ago)

Also, any chance you could see if these other start locations work:
FEMA Entrance
FEMA Camp
Electronics Store
Gas Station
Clothing Store

They are from More Classes and Scenarios mod, which I put into my mod. I suspect that mod being marked as "obsolete" is why mansion starts don't work, for instance.

**Comment by miu135** [comment]
I'm using version 0.E Ellison tiles
Build number #10478

The FEMA starts seems to work just fine
![cdda4femaentrance](https://user-images.githubusercontent.com/54433550/79534206-26abb300-80a4-11ea-96b6-10de3dcdf405.PNG)

![cdda5femacamp](https://user-images.githubusercontent.com/54433550/79534214-2b706700-80a4-11ea-978f-e1b5958c3e95.PNG)

Though I can't seem to find the electronics store, clothing store and the gas station start anywhere probably because as you said, they are from the More Classes and Scenarios mod which I don't have.

Also I found out there's a youkai mod on the wiki, would that be compatible with this mod?

**Comment by miu135** [comment]
Edit: nevermind I'm a dummy and just made everything work now

**Comment by Taberone** [comment]
How did it work
Might be useful to find out how to fix it (or what caused it) in case it happens again

Also no idea what the youkai mod is, but I guess it MIGHT be compatible? Seems to add in new enemies, that's all.

**Comment by miu135** [comment]
Turns out I just need to update my game to the latest experimental and use the mods on the txt that I miss that's all. I'm kinda new to CDDA on PC so expect me missing out simple stuffs
