### ISSUE TITLE
Seiga doesn't spawn with a dormant minion

### ISSUE THREAD

**Issue by miu135** [Taberone/Cataclysm-DDA-Touhou-Mod#28]
Is this supposed to happen?
I'm new to the necromancy mod and don't know what am I supposed to do

**Comment by Taberone** [comment]
I think that got removed, I can't find it in the debug item spawning menu

**Comment by miu135** [comment]
I just found out that magiclysm has spells related to summoning non-permanent zombies so maybe you can use that instead

**Comment by Taberone** [comment]
Not sure how to get the Seiga profession (Wicked Hermit) to spawn with the summon zombie spell but I'll look into it

**Comment by miu135** [comment]
Might as well rework the other professions too since spellcasting is in the game now.

**Comment by Taberone** [comment]
Will do, just need to figure out what spells they should spawn with and stuff. Wicked Hermit should definitely spawn with that zombie-summon spell. Think I've figured out how to get professions to spawn with spells, but I need to test it out tomorrow.

**Comment by miu135** [comment]
Looking forward to it!
