### ISSUE TITLE
Have you tried the japanese mod?

### ISSUE THREAD

**Issue by miu135** [Taberone/Cataclysm-DDA-Touhou-Mod#34]
Maybe you could borrow some things from there?

**Comment by Taberone** [comment]
Japanese mod? I've barely heard of them, but a lot of them require Lua (which is no longer supported by CDDA). Which things in particular?

**Comment by miu135** [comment]
I'm talking about the one on this wiki
https://w.atwiki.jp/cataclyj/sp/pages/224.html
I dunno if this is the one you're talking about or not
